// The fictional applicant the live surveys fill forms as (never a real person).
export const SURVEY_PROFILE = {
  personal: {
    prefix: 'Mr',
    firstName: 'Alex',
    lastName: 'Morgan',
    preferredName: 'Alex',
    pronouns: 'he/him',
    dob: '2005-03-14',
    nationality: 'British',
  },
  contact: { email: 'alex.morgan.jtf@example.com', phoneCountryCode: '+44', phone: '7700 900123', phoneType: 'Mobile' },
  address: {
    line1: '12 Gower Street',
    line2: '',
    city: 'London',
    state: 'Greater London',
    postalCode: 'WC1E 6BT',
    country: 'United Kingdom',
    organization: '',
  },
  links: {
    linkedin: 'https://www.linkedin.com/in/alexmorgan-jtf',
    github: 'https://github.com/alexmorgan-jtf',
    portfolio: '',
    website: '',
    twitter: '',
  },
  job: {
    yearsExperience: '1',
    authorized: 'Yes',
    sponsorship: 'No',
    relocate: 'Yes',
    over18: 'Yes',
    salary: '',
    noticePeriod: 'None',
    nonCompete: 'No',
    startDate: '2027-06-28',
    referralSource: 'Trackr',
    locations: 'London, New York',
    otherOffers: 'No',
    clearance: 'None',
    clearanceEligible: 'Yes',
    onsite: 'Yes',
    adjustments: 'No',
  },
  eeo: {
    gender: 'Male',
    race: 'White – British',
    hispanic: 'No',
    veteran: 'No',
    disability: 'No',
    sexualOrientation: 'Heterosexual / straight',
    genderIdentitySame: 'Yes',
    religion: 'No religion or belief',
    neurodivergent: 'No',
    schoolType: 'State school (non-selective)',
    freeSchoolMeals: 'No',
    parentsDegree: 'Yes',
    parentOccupation: 'Professional',
    postcodeAt14: 'N1 9GU',
    careLeaver: 'No',
    carer: 'No',
    refugee: 'No',
    bursary: 'No',
  },
  compliance: {
    previouslyEmployed: 'No',
    previouslyApplied: 'No',
    relatives: 'No',
    relativesDetails: '',
    governmentOfficial: 'No',
    familyGovernmentOfficial: 'No',
    governmentDetails: '',
  },
  education: [
    {
      school: 'University College London',
      degree: 'BSc',
      field: 'Economics',
      gpa: '2:1',
      location: 'London, UK',
      startDate: '2024-09',
      endDate: '2027-06',
    },
    {
      school: 'Highbury Grove School',
      degree: 'A-levels',
      field: 'Mathematics, Further Mathematics, Economics',
      gpa: 'A*A*A',
      location: 'London, UK',
      startDate: '2017-09',
      endDate: '2023-07',
    },
  ],
  experience: [
    {
      company: 'Finch & Partners',
      title: 'Summer Analyst Intern',
      location: 'London',
      startDate: '2025-07',
      endDate: '2025-08',
      current: false,
      description:
        'Built an Excel model of 40 listed retailers’ margins for a sector note; cleaned three years of sales data in Python.',
    },
    {
      company: 'UCL Economics & Finance Society',
      title: 'Treasurer',
      location: 'London',
      startDate: '2025-09',
      endDate: '',
      current: true,
      description: 'Run a £12,000 budget and the society’s sponsorship talks with four firms.',
    },
  ],
  skills: 'Python, Excel, SQL, Financial modelling, Bloomberg',
  languages: 'English, Spanish',
  summary:
    'Second-year Economics student at UCL with an internship in equity research and a treasurer role, looking for a 2027 role in finance.',
  coverLetter: '',
  customAnswers: [],
};

export const SURVEY_CV = [
  'Alex Morgan',
  'alex.morgan.jtf@example.com | +44 7700 900123 | London, UK | linkedin.com/in/alexmorgan-jtf',
  '',
  'EDUCATION',
  'University College London, BSc Economics, Sep 2024 – Jun 2027. On track for a First (72% average in year one).',
  'Modules: Econometrics, Microeconomics, Macroeconomics, Statistics, Corporate Finance.',
  'Highbury Grove School, A-levels: Mathematics (A*), Further Mathematics (A*), Economics (A), 2023.',
  '',
  'EXPERIENCE',
  'Finch & Partners, Summer Analyst Intern, Jul 2025 – Aug 2025, London',
  '• Built an Excel model of 40 listed UK retailers’ margins used in the team’s sector note.',
  '• Cleaned three years of store-level sales data in Python (pandas) and wrote the summary charts.',
  'UCL Economics & Finance Society, Treasurer, Sep 2025 – present',
  '• Run a £12,000 annual budget and lead sponsorship talks with four firms.',
  '• Organised a trading game for 120 students with a market-making simulation.',
  'Saturday job, Waitrose, Customer Assistant, 2021 – 2023',
  '• Trained four new starters and handled the till close.',
  '',
  'PROJECTS',
  '• Pairs trading backtest in Python on FTSE 100 stocks; wrote up why it stopped working after costs.',
  '',
  'SKILLS',
  'Python (pandas, NumPy), Excel, SQL, Bloomberg Market Concepts certificate, Spanish (conversational).',
  'Interests: chess (club captain), half-marathons, economic history.',
].join('\n');
